#!/bin/sh

if [[ ${SERVER_PASSWORD+x} ]]; then
    sed -i -e "s/serverpassword=/serverpassword=$SERVER_PASSWORD/" /etc/murmur/murmur.ini
fi

if [[ ${MUMBLE_HOSTNAME+x} ]]; then
    sed -i -e "s/#registerHostname=/registerHostname=$MUMBLE_HOSTNAME/" /etc/murmur/murmur.ini
fi

chown -R murmur:nobody /etc/murmur

if [[ ! -f /opt/murmur/supwd ]]; then

    STORAGE_LOCATION='/opt/murmur/supwd'
    SUPERUSER_PASSWORD=`pwgen -c -n -1 15`
    echo $SUPERUSER_PASSWORD > $STORAGE_LOCATION
    chmod 400 $STORAGE_LOCATION

    /opt/murmur/murmur.x86 -ini /etc/murmur/murmur.ini -supw $SUPERUSER_PASSWORD
    sleep 3

    echo "============================================="
    echo
    echo "[ ! ] SUPERUSER PASSWORD: $SUPERUSER_PASSWORD"
    echo
    echo "============================================="
    echo
fi

# start murmurd
/opt/murmur/murmur.x86 -fg -v -ini /etc/murmur/murmur.ini
